/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/clouddms/v1/clouddms_resources.proto

package com.google.cloud.clouddms.v1;

public final class ClouddmsResourcesProto {
  private ClouddmsResourcesProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_SslConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_SslConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_MySqlConnectionProfile_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_MySqlConnectionProfile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_PostgreSqlConnectionProfile_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_PostgreSqlConnectionProfile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_CloudSqlConnectionProfile_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_CloudSqlConnectionProfile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_SqlAclEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_SqlAclEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_SqlIpConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_SqlIpConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_CloudSqlSettings_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_CloudSqlSettings_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_CloudSqlSettings_UserLabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_CloudSqlSettings_UserLabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_CloudSqlSettings_DatabaseFlagsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_CloudSqlSettings_DatabaseFlagsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_StaticIpConnectivity_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_StaticIpConnectivity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_ReverseSshConnectivity_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_ReverseSshConnectivity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_VpcPeeringConnectivity_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_VpcPeeringConnectivity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_DatabaseType_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_DatabaseType_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_MigrationJob_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_MigrationJob_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_MigrationJob_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_MigrationJob_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_ConnectionProfile_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_ConnectionProfile_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_ConnectionProfile_LabelsEntry_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_ConnectionProfile_LabelsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_MigrationJobVerificationError_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_MigrationJobVerificationError_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n"
          + "1google/cloud/clouddms/v1/clouddms_reso"
          + "urces.proto\022\030google.cloud.clouddms.v1\032\037g"
          + "oogle/api/field_behavior.proto\032\031google/a"
          + "pi/resource.proto\032\036google/protobuf/durat"
          + "ion.proto\032\037google/protobuf/timestamp.pro"
          + "to\032\036google/protobuf/wrappers.proto\032\027google/rpc/status.proto\032\034google/api/annotations.proto\"\356\001\n"
          + "\tSslConfig\022>\n"
          + "\004type\030\001"
          + " \001(\0162+.google.cloud.clouddms.v1.SslConfig.SslTypeB\003\340A\003\022\027\n\n"
          + "client_key\030\002 \001(\tB\003\340A\004\022\037\n"
          + "\022client_certificate\030\003 \001(\tB\003\340A\004\022\036\n"
          + "\016ca_certificate\030\004 \001(\tB\006\340A\004\340A\002\"G\n"
          + "\007SslType\022\030\n"
          + "\024SSL_TYPE_UNSPECIFIED\020\000\022\017\n"
          + "\013SERVER_ONLY\020\001\022\021\n\r"
          + "SERVER_CLIENT\020\002\"\322\001\n"
          + "\026MySqlConnectionProfile\022\021\n"
          + "\004host\030\001 \001(\tB\003\340A\002\022\021\n"
          + "\004port\030\002 \001(\005B\003\340A\002\022\025\n"
          + "\010username\030\003 \001(\tB\003\340A\002\022\030\n"
          + "\010password\030\004 \001(\tB\006\340A\004\340A\002\022\031\n"
          + "\014password_set\030\005 \001(\010B\003\340A\003\0220\n"
          + "\003ssl\030\006 \001(\0132#.google.cloud.clouddms.v1.SslConfig\022\024\n"
          + "\014cloud_sql_id\030\007 \001(\t\"\327\001\n"
          + "\033PostgreSqlConnectionProfile\022\021\n"
          + "\004host\030\001 \001(\tB\003\340A\002\022\021\n"
          + "\004port\030\002 \001(\005B\003\340A\002\022\025\n"
          + "\010username\030\003 \001(\tB\003\340A\002\022\030\n"
          + "\010password\030\004 \001(\tB\006\340A\004\340A\002\022\031\n"
          + "\014password_set\030\005 \001(\010B\003\340A\003\0220\n"
          + "\003ssl\030\006 \001(\0132#.google.cloud.clouddms.v1.SslConfig\022\024\n"
          + "\014cloud_sql_id\030\007 \001(\t\"\252\001\n"
          + "\031CloudSqlConnectionProfile\022\031\n"
          + "\014cloud_sql_id\030\001 \001(\tB\003\340A\003\022A\n"
          + "\010settings\030\002"
          + " \001(\0132*.google.cloud.clouddms.v1.CloudSqlSettingsB\003\340A\005\022\027\n\n"
          + "private_ip\030\003 \001(\tB\003\340A\003\022\026\n"
          + "\tpublic_ip\030\004 \001(\tB\003\340A\003\"\233\001\n"
          + "\013SqlAclEntry\022\r\n"
          + "\005value\030\001 \001(\t\0221\n"
          + "\013expire_time\030\n"
          + " \001(\0132\032.google.protobuf.TimestampH\000\022-\n"
          + "\003ttl\030\013 \001(\0132\031.google.protobuf.DurationB\003\340A\004H\000\022\r\n"
          + "\005label\030\003 \001(\tB\014\n\n"
          + "expiration\"\314\001\n"
          + "\013SqlIpConfig\022/\n"
          + "\013enable_ipv4\030\001 \001(\0132\032.google.protobuf.BoolValue\022\027\n"
          + "\017private_network\030\002 \001(\t\022/\n"
          + "\013require_ssl\030\003 \001(\0132\032.google.protobuf.BoolValue\022B\n"
          + "\023authorized_networks\030\004 \003(\0132%.google.cloud.clouddms.v1.SqlAclEntry\"\372"
          + "\t\n"
          + "\020CloudSqlSettings\022W\n"
          + "\020database_version\030\001"
          + " \001(\0162=.google.cloud.clouddms.v1.CloudSqlSettings.SqlDatabaseVersion\022O\n"
          + "\013user_labels\030\002"
          + " \003(\0132:.google.cloud.clouddms.v1.CloudSqlSettings.UserLabelsEntry\022\014\n"
          + "\004tier\030\003 \001(\t\022>\n"
          + "\031storage_auto_resize_limit\030\004 \001(\0132\033.google.protobuf.Int64Value\022Y\n"
          + "\021activation_policy\030\005"
          + " \001(\0162>.google.cloud.clouddms.v1.CloudSqlSettings.SqlActivationPolicy\0228\n"
          + "\tip_config\030\006 \001(\0132%.google.cloud.clouddms.v1.SqlIpConfig\0229\n"
          + "\025auto_storage_increase\030\007 \001(\0132\032.google.protobuf.BoolValue\022U\n"
          + "\016database_flags\030\010"
          + " \003(\0132=.google.cloud.clouddms.v1.CloudSqlSettings.DatabaseFlagsEntry\022R\n"
          + "\016data_disk_type\030\t"
          + " \001(\0162:.google.cloud.clouddms.v1.CloudSqlSettings.SqlDataDiskType\0226\n"
          + "\021data_disk_size_gb\030\n"
          + " \001(\0132\033.google.protobuf.Int64Value\022\014\n"
          + "\004zone\030\013 \001(\t\022\021\n"
          + "\tsource_id\030\014 \001(\t\022\032\n\r"
          + "root_password\030\r"
          + " \001(\tB\003\340A\004\022\036\n"
          + "\021root_password_set\030\016 \001(\010B\003\340A\003\022\021\n"
          + "\tcollation\030\017 \001(\t\0321\n"
          + "\017UserLabelsEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001\0324\n"
          + "\022DatabaseFlagsEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001\"S\n"
          + "\023SqlActivationPolicy\022%\n"
          + "!SQL_ACTIVATION_POLICY_UNSPECIFIED\020\000\022\n\n"
          + "\006ALWAYS\020\001\022\t\n"
          + "\005NEVER\020\002\"M\n"
          + "\017SqlDataDiskType\022\"\n"
          + "\036SQL_DATA_DISK_TYPE_UNSPECIFIED\020\000\022\n\n"
          + "\006PD_SSD\020\001\022\n\n"
          + "\006PD_HDD\020\002\"\275\001\n"
          + "\022SqlDatabaseVersion\022$\n"
          + " SQL_DATABASE_VERSION_UNSPECIFIED\020\000\022\r\n"
          + "\tMYSQL_5_6\020\001\022\r\n"
          + "\tMYSQL_5_7\020\002\022\020\n"
          + "\014POSTGRES_9_6\020\003\022\017\n"
          + "\013POSTGRES_11\020\004\022\017\n"
          + "\013POSTGRES_10\020\005\022\r\n"
          + "\tMYSQL_8_0\020\006\022\017\n"
          + "\013POSTGRES_12\020\007\022\017\n"
          + "\013POSTGRES_13\020\010\"\026\n"
          + "\024StaticIpConnectivity\"[\n"
          + "\026ReverseSshConnectivity\022\022\n"
          + "\005vm_ip\030\001 \001(\tB\003\340A\002\022\024\n"
          + "\007vm_port\030\002 \001(\005B\003\340A\002\022\n\n"
          + "\002vm\030\003 \001(\t\022\013\n"
          + "\003vpc\030\004 \001(\t\"%\n"
          + "\026VpcPeeringConnectivity\022\013\n"
          + "\003vpc\030\001 \001(\t\"\206\001\n"
          + "\014DatabaseType\022<\n"
          + "\010provider\030\001 \001(\0162*.google.cloud.clouddms.v1.DatabaseProvider\0228\n"
          + "\006engine\030\002 \001(\0162(.google.cloud.clouddms.v1.DatabaseEngine\"\354\014\n"
          + "\014MigrationJob\022\014\n"
          + "\004name\030\001 \001(\t\0224\n"
          + "\013create_time\030\002 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\0224\n"
          + "\013update_time\030\003 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\022B\n"
          + "\006labels\030\004"
          + " \003(\01322.google.cloud.clouddms.v1.MigrationJob.LabelsEntry\022\024\n"
          + "\014display_name\030\005 \001(\t\022;\n"
          + "\005state\030\006 \001(\0162,.google.cloud.clouddms.v1.MigrationJob.State\022@\n"
          + "\005phase\030\007"
          + " \001(\0162,.google.cloud.clouddms.v1.MigrationJob.PhaseB\003\340A\003\022>\n"
          + "\004type\030\010"
          + " \001(\0162+.google.cloud.clouddms.v1.MigrationJob.TypeB\003\340A\002\022\021\n"
          + "\tdump_path\030\t \001(\t\022\023\n"
          + "\006source\030\n"
          + " \001(\tB\003\340A\002\022\030\n"
          + "\013destination\030\013 \001(\tB\003\340A\002\022T\n"
          + "\030reverse_ssh_connectivity\030e"
          + " \001(\01320.google.cloud.clouddms.v1.ReverseSshConnectivityH\000\022T\n"
          + "\030vpc_peering_connectivity\030f"
          + " \001(\01320.google.cloud.clouddms.v1.VpcPeeringConnectivityH\000\022P\n"
          + "\026static_ip_connectivity\030g"
          + " \001(\0132..google.cloud.clouddms.v1.StaticIpConnectivityH\000\0220\n"
          + "\010duration\030\014 \001(\0132\031.google.protobuf.DurationB\003\340A\003\022&\n"
          + "\005error\030\r"
          + " \001(\0132\022.google.rpc.StatusB\003\340A\003\022?\n"
          + "\017source_database\030\016 \001(\0132&.google.cloud.clouddms.v1.DatabaseType\022D\n"
          + "\024destination_database\030\017"
          + " \001(\0132&.google.cloud.clouddms.v1.DatabaseType\0221\n"
          + "\010end_time\030\020 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\032-\n"
          + "\013LabelsEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001\"\361\001\n"
          + "\005State\022\025\n"
          + "\021STATE_UNSPECIFIED\020\000\022\017\n"
          + "\013MAINTENANCE\020\001\022\t\n"
          + "\005DRAFT\020\002\022\014\n"
          + "\010CREATING\020\003\022\017\n"
          + "\013NOT_STARTED\020\004\022\013\n"
          + "\007RUNNING\020\005\022\n\n"
          + "\006FAILED\020\006\022\r\n"
          + "\tCOMPLETED\020\007\022\014\n"
          + "\010DELETING\020\010\022\014\n"
          + "\010STOPPING\020\t\022\013\n"
          + "\007STOPPED\020\n"
          + "\022\013\n"
          + "\007DELETED\020\013\022\014\n"
          + "\010UPDATING\020\014\022\014\n"
          + "\010STARTING\020\r"
          + "\022\016\n\n"
          + "RESTARTING\020\016\022\014\n"
          + "\010RESUMING\020\017\"\216\001\n"
          + "\005Phase\022\025\n"
          + "\021PHASE_UNSPECIFIED\020\000\022\r\n"
          + "\tFULL_DUMP\020\001\022\007\n"
          + "\003CDC\020\002\022\027\n"
          + "\023PROMOTE_IN_PROGRESS\020\003\022%\n"
          + "!WAITING_FOR_SOURCE_WRITES_TO_STOP\020\004\022\026\n"
          + "\022PREPARING_THE_DUMP\020\005\":\n"
          + "\004Type\022\024\n"
          + "\020TYPE_UNSPECIFIED\020\000\022\014\n"
          + "\010ONE_TIME\020\001\022\016\n\n"
          + "CONTINUOUS\020\002:u\352Ar\n"
          + ")datamigration.googleapis.com/MigrationJob\022Eprojects/{project}/locations/{location}/migrationJobs/{migration_job}B\016\n"
          + "\014connectivity\"\263\007\n"
          + "\021ConnectionProfile\022\014\n"
          + "\004name\030\001 \001(\t\0224\n"
          + "\013create_time\030\002 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\0224\n"
          + "\013update_time\030\003 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\022G\n"
          + "\006labels\030\004"
          + " \003(\01327.google.cloud.clouddms.v1.ConnectionProfile.LabelsEntry\022@\n"
          + "\005state\030\005"
          + " \001(\01621.google.cloud.clouddms.v1.ConnectionProfile.State\022\024\n"
          + "\014display_name\030\006 \001(\t\022A\n"
          + "\005mysql\030d"
          + " \001(\01320.google.cloud.clouddms.v1.MySqlConnectionProfileH\000\022K\n\n"
          + "postgresql\030e"
          + " \001(\01325.google.cloud.clouddms.v1.PostgreSqlConnectionProfileH\000\022G\n"
          + "\010cloudsql\030f"
          + " \001(\01323.google.cloud.clouddms.v1.CloudSqlConnectionProfileH\000\022&\n"
          + "\005error\030\007 \001(\0132\022.google.rpc.StatusB\003\340A\003\022<\n"
          + "\010provider\030\010 \001(\0162*.google.cloud.clouddms.v1.DatabaseProvider\032-\n"
          + "\013LabelsEntry\022\013\n"
          + "\003key\030\001 \001(\t\022\r\n"
          + "\005value\030\002 \001(\t:\0028\001\"w\n"
          + "\005State\022\025\n"
          + "\021STATE_UNSPECIFIED\020\000\022\t\n"
          + "\005DRAFT\020\001\022\014\n"
          + "\010CREATING\020\002\022\t\n"
          + "\005READY\020\003\022\014\n"
          + "\010UPDATING\020\004\022\014\n"
          + "\010DELETING\020\005\022\013\n"
          + "\007DELETED\020\006\022\n\n"
          + "\006FAILED\020\007:\205\001\352A\201\001\n"
          + ".datamigration.googleapis.com/ConnectionProf"
          + "ile\022Oprojects/{project}/locations/{location}/connectionProfiles/{connection_profile}B\024\n"
          + "\022connection_profile\"\320\006\n"
          + "\035MigrationJobVerificationError\022Z\n\n"
          + "error_code\030\001"
          + " \001(\0162A.google.cloud.clouddms.v1.MigrationJobVerificationError.ErrorCodeB\003\340A\003\022\032\n\r"
          + "error_message\030\002 \001(\tB\003\340A\003\022!\n"
          + "\024error_detail_message\030\003 \001(\tB\003\340A\003\"\223\005\n"
          + "\tErrorCode\022\032\n"
          + "\026ERROR_CODE_UNSPECIFIED\020\000\022\026\n"
          + "\022CONNECTION_FAILURE\020\001\022\032\n"
          + "\026AUTHENTICATION_FAILURE\020\002\022%\n"
          + "!INVALID_CONNECTION_PROFILE_CONFIG\020\003\022\033\n"
          + "\027VERSION_INCOMPATIBILITY\020\004\022,\n"
          + "(CONNECTION_PROFILE_TYPES_INCOMPATIBILITY\020\005\022\032\n"
          + "\026NO_PGLOGICAL_INSTALLED\020\007\022!\n"
          + "\035PGLOGICAL_NODE_ALREADY_EXISTS\020\010\022\025\n"
          + "\021INVALID_WAL_LEVEL\020\t\022\"\n"
          + "\036INVALID_SHARED_PRELOAD_LIBRARY\020\n"
          + "\022&\n"
          + "\"INSUFFICIENT_MAX_REPLICATION_SLOTS\020\013\022 \n"
          + "\034INSUFFICIENT_MAX_WAL_SENDERS\020\014\022%\n"
          + "!INSUFFICIENT_MAX_WORKER_PROCESSES\020\r"
          + "\022\032\n"
          + "\026UNSUPPORTED_EXTENSIONS\020\016\022\036\n"
          + "\032UNSUPPORTED_MIGRATION_TYPE\020\017\022#\n"
          + "\037INVALID_RDS_LOGICAL_REPLICATION\020\020\022\031\n"
          + "\025UNSUPPORTED_GTID_MODE\020\021\022 \n"
          + "\034UNSUPPORTED_TABLE_DEFINITION\020\022\022\027\n"
          + "\023UNSUPPORTED_DEFINER\020\023\022\"\n"
          + "\036CANT_RESTART_RUNNING_MIGRATION\020\025*L\n"
          + "\016DatabaseEngine\022\037\n"
          + "\033DATABASE_ENGINE_UNSPECIFIED\020\000\022\t\n"
          + "\005MYSQL\020\001\022\016\n\n"
          + "POSTGRESQL\020\002*L\n"
          + "\020DatabaseProvider\022!\n"
          + "\035DATABASE_PROVIDER_UNSPECIFIED\020\000\022\014\n"
          + "\010CLOUDSQL\020\001\022\007\n"
          + "\003RDS\020\002B\316\001\n"
          + "\034com.google.cloud.clouddms.v1B\026ClouddmsReso"
          + "urcesProtoP\001Z@google.golang.org/genproto"
          + "/googleapis/cloud/clouddms/v1;clouddms\252\002"
          + "\030Google.Cloud.CloudDms.V1\312\002\030Google\\Cloud"
          + "\\CloudDms\\V1\352\002\033Google::Cloud::CloudDMS::V1b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.protobuf.DurationProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
              com.google.protobuf.WrappersProto.getDescriptor(),
              com.google.rpc.StatusProto.getDescriptor(),
              com.google.api.AnnotationsProto.getDescriptor(),
            });
    internal_static_google_cloud_clouddms_v1_SslConfig_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_clouddms_v1_SslConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_SslConfig_descriptor,
            new java.lang.String[] {
              "Type", "ClientKey", "ClientCertificate", "CaCertificate",
            });
    internal_static_google_cloud_clouddms_v1_MySqlConnectionProfile_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_clouddms_v1_MySqlConnectionProfile_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_MySqlConnectionProfile_descriptor,
            new java.lang.String[] {
              "Host", "Port", "Username", "Password", "PasswordSet", "Ssl", "CloudSqlId",
            });
    internal_static_google_cloud_clouddms_v1_PostgreSqlConnectionProfile_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_clouddms_v1_PostgreSqlConnectionProfile_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_PostgreSqlConnectionProfile_descriptor,
            new java.lang.String[] {
              "Host", "Port", "Username", "Password", "PasswordSet", "Ssl", "CloudSqlId",
            });
    internal_static_google_cloud_clouddms_v1_CloudSqlConnectionProfile_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_clouddms_v1_CloudSqlConnectionProfile_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_CloudSqlConnectionProfile_descriptor,
            new java.lang.String[] {
              "CloudSqlId", "Settings", "PrivateIp", "PublicIp",
            });
    internal_static_google_cloud_clouddms_v1_SqlAclEntry_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_clouddms_v1_SqlAclEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_SqlAclEntry_descriptor,
            new java.lang.String[] {
              "Value", "ExpireTime", "Ttl", "Label", "Expiration",
            });
    internal_static_google_cloud_clouddms_v1_SqlIpConfig_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_clouddms_v1_SqlIpConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_SqlIpConfig_descriptor,
            new java.lang.String[] {
              "EnableIpv4", "PrivateNetwork", "RequireSsl", "AuthorizedNetworks",
            });
    internal_static_google_cloud_clouddms_v1_CloudSqlSettings_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_clouddms_v1_CloudSqlSettings_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_CloudSqlSettings_descriptor,
            new java.lang.String[] {
              "DatabaseVersion",
              "UserLabels",
              "Tier",
              "StorageAutoResizeLimit",
              "ActivationPolicy",
              "IpConfig",
              "AutoStorageIncrease",
              "DatabaseFlags",
              "DataDiskType",
              "DataDiskSizeGb",
              "Zone",
              "SourceId",
              "RootPassword",
              "RootPasswordSet",
              "Collation",
            });
    internal_static_google_cloud_clouddms_v1_CloudSqlSettings_UserLabelsEntry_descriptor =
        internal_static_google_cloud_clouddms_v1_CloudSqlSettings_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_clouddms_v1_CloudSqlSettings_UserLabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_CloudSqlSettings_UserLabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_clouddms_v1_CloudSqlSettings_DatabaseFlagsEntry_descriptor =
        internal_static_google_cloud_clouddms_v1_CloudSqlSettings_descriptor
            .getNestedTypes()
            .get(1);
    internal_static_google_cloud_clouddms_v1_CloudSqlSettings_DatabaseFlagsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_CloudSqlSettings_DatabaseFlagsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_clouddms_v1_StaticIpConnectivity_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_clouddms_v1_StaticIpConnectivity_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_StaticIpConnectivity_descriptor,
            new java.lang.String[] {});
    internal_static_google_cloud_clouddms_v1_ReverseSshConnectivity_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_clouddms_v1_ReverseSshConnectivity_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_ReverseSshConnectivity_descriptor,
            new java.lang.String[] {
              "VmIp", "VmPort", "Vm", "Vpc",
            });
    internal_static_google_cloud_clouddms_v1_VpcPeeringConnectivity_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_clouddms_v1_VpcPeeringConnectivity_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_VpcPeeringConnectivity_descriptor,
            new java.lang.String[] {
              "Vpc",
            });
    internal_static_google_cloud_clouddms_v1_DatabaseType_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_clouddms_v1_DatabaseType_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_DatabaseType_descriptor,
            new java.lang.String[] {
              "Provider", "Engine",
            });
    internal_static_google_cloud_clouddms_v1_MigrationJob_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_cloud_clouddms_v1_MigrationJob_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_MigrationJob_descriptor,
            new java.lang.String[] {
              "Name",
              "CreateTime",
              "UpdateTime",
              "Labels",
              "DisplayName",
              "State",
              "Phase",
              "Type",
              "DumpPath",
              "Source",
              "Destination",
              "ReverseSshConnectivity",
              "VpcPeeringConnectivity",
              "StaticIpConnectivity",
              "Duration",
              "Error",
              "SourceDatabase",
              "DestinationDatabase",
              "EndTime",
              "Connectivity",
            });
    internal_static_google_cloud_clouddms_v1_MigrationJob_LabelsEntry_descriptor =
        internal_static_google_cloud_clouddms_v1_MigrationJob_descriptor.getNestedTypes().get(0);
    internal_static_google_cloud_clouddms_v1_MigrationJob_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_MigrationJob_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_clouddms_v1_ConnectionProfile_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_cloud_clouddms_v1_ConnectionProfile_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_ConnectionProfile_descriptor,
            new java.lang.String[] {
              "Name",
              "CreateTime",
              "UpdateTime",
              "Labels",
              "State",
              "DisplayName",
              "Mysql",
              "Postgresql",
              "Cloudsql",
              "Error",
              "Provider",
              "ConnectionProfile",
            });
    internal_static_google_cloud_clouddms_v1_ConnectionProfile_LabelsEntry_descriptor =
        internal_static_google_cloud_clouddms_v1_ConnectionProfile_descriptor
            .getNestedTypes()
            .get(0);
    internal_static_google_cloud_clouddms_v1_ConnectionProfile_LabelsEntry_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_ConnectionProfile_LabelsEntry_descriptor,
            new java.lang.String[] {
              "Key", "Value",
            });
    internal_static_google_cloud_clouddms_v1_MigrationJobVerificationError_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_google_cloud_clouddms_v1_MigrationJobVerificationError_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_MigrationJobVerificationError_descriptor,
            new java.lang.String[] {
              "ErrorCode", "ErrorMessage", "ErrorDetailMessage",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.ResourceProto.resource);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.protobuf.DurationProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
    com.google.rpc.StatusProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
