/*
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/cloud/clouddms/v1/clouddms.proto

package com.google.cloud.clouddms.v1;

public final class ClouddmsProto {
  private ClouddmsProto() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions((com.google.protobuf.ExtensionRegistryLite) registry);
  }

  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_ListMigrationJobsRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_ListMigrationJobsRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_ListMigrationJobsResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_ListMigrationJobsResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_GetMigrationJobRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_GetMigrationJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_CreateMigrationJobRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_CreateMigrationJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_UpdateMigrationJobRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_UpdateMigrationJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_DeleteMigrationJobRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_DeleteMigrationJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_StartMigrationJobRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_StartMigrationJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_StopMigrationJobRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_StopMigrationJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_ResumeMigrationJobRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_ResumeMigrationJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_PromoteMigrationJobRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_PromoteMigrationJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_VerifyMigrationJobRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_VerifyMigrationJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_RestartMigrationJobRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_RestartMigrationJobRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_GenerateSshScriptRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_GenerateSshScriptRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_VmCreationConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_VmCreationConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_VmSelectionConfig_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_VmSelectionConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_SshScript_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_SshScript_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_ListConnectionProfilesRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_ListConnectionProfilesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_ListConnectionProfilesResponse_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_ListConnectionProfilesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_GetConnectionProfileRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_GetConnectionProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_CreateConnectionProfileRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_CreateConnectionProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_UpdateConnectionProfileRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_UpdateConnectionProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_DeleteConnectionProfileRequest_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_DeleteConnectionProfileRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
      internal_static_google_cloud_clouddms_v1_OperationMetadata_descriptor;
  static final com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_google_cloud_clouddms_v1_OperationMetadata_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
    return descriptor;
  }

  private static com.google.protobuf.Descriptors.FileDescriptor descriptor;

  static {
    java.lang.String[] descriptorData = {
      "\n"
          + "\'google/cloud/clouddms/v1/clouddms.prot"
          + "o\022\030google.cloud.clouddms.v1\032\034google/api/"
          + "annotations.proto\032\027google/api/client.pro"
          + "to\032\037google/api/field_behavior.proto\032\031goo"
          + "gle/api/resource.proto\0321google/cloud/clouddms/v1/clouddms_resources.proto\032#google/longrunning/operations.proto\032"
          + " google/protobuf/field_mask.proto\032\037google/protobuf/timestamp.proto\"\246\001\n"
          + "\030ListMigrationJobsRequest\022A\n"
          + "\006parent\030\001 \001("
          + "\tB1\340A\002\372A+\022)datamigration.googleapis.com/MigrationJob\022\021\n"
          + "\tpage_size\030\002 \001(\005\022\022\n\n"
          + "page_token\030\003 \001(\t\022\016\n"
          + "\006filter\030\004 \001(\t\022\020\n"
          + "\010order_by\030\005 \001(\t\"\211\001\n"
          + "\031ListMigrationJobsResponse\022>\n"
          + "\016migration_jobs\030\001 \003(\0132&.google.cloud.clouddms.v1.MigrationJob\022\027\n"
          + "\017next_page_token\030\002 \001(\t\022\023\n"
          + "\013unreachable\030\003 \003(\t\"Y\n"
          + "\026GetMigrationJobRequest\022?\n"
          + "\004name\030\001 \001(\tB1\340A\002\372A+\n"
          + ")datamigration.googleapis.com/MigrationJob\"\325\001\n"
          + "\031CreateMigrationJobRequest\022A\n"
          + "\006parent\030\001 \001("
          + "\tB1\340A\002\372A+\022)datamigration.googleapis.com/MigrationJob\022\035\n"
          + "\020migration_job_id\030\002 \001(\tB\003\340A\002\022B\n\r"
          + "migration_job\030\003"
          + " \001(\0132&.google.cloud.clouddms.v1.MigrationJobB\003\340A\002\022\022\n\n"
          + "request_id\030\004 \001(\t\"\251\001\n"
          + "\031UpdateMigrationJobRequest\0224\n"
          + "\013update_mask\030\001 \001(\0132\032.google.protobuf.FieldMaskB\003\340A\002\022B\n"
          + "\r"
          + "migration_job\030\002"
          + " \001(\0132&.google.cloud.clouddms.v1.MigrationJobB\003\340A\002\022\022\n\n"
          + "request_id\030\003 \001(\t\"\177\n"
          + "\031DeleteMigrationJobRequest\022?\n"
          + "\004name\030\001 \001(\tB1\340A\002\372A+\n"
          + ")datamigration.googleapis.com/MigrationJob\022\022\n\n"
          + "request_id\030\002 \001(\t\022\r\n"
          + "\005force\030\003 \001(\010\"X\n"
          + "\030StartMigrationJobRequest\022<\n"
          + "\004name\030\001 \001(\tB.\372A+\n"
          + ")datamigration.googleapis.com/MigrationJob\"W\n"
          + "\027StopMigrationJobRequest\022<\n"
          + "\004name\030\001 \001(\tB.\372A+\n"
          + ")datamigration.googleapis.com/MigrationJob\"Y\n"
          + "\031ResumeMigrationJobRequest\022<\n"
          + "\004name\030\001 \001(\tB.\372A+\n"
          + ")datamigration.googleapis.com/MigrationJob\"Z\n"
          + "\032PromoteMigrationJobRequest\022<\n"
          + "\004name\030\001 \001(\tB.\372A+\n"
          + ")datamigration.googleapis.com/MigrationJob\"Y\n"
          + "\031VerifyMigrationJobRequest\022<\n"
          + "\004name\030\001 \001(\tB.\372A+\n"
          + ")datamigration.googleapis.com/MigrationJob\"Z\n"
          + "\032RestartMigrationJobRequest\022<\n"
          + "\004name\030\001 \001(\tB.\372A+\n"
          + ")datamigration.googleapis.com/MigrationJob\"\246\002\n"
          + "\030GenerateSshScriptRequest\022E\n\r"
          + "migration_job\030\001 \001(\tB.\372A+\n"
          + ")datamigration.googleapis.com/MigrationJob\022\017\n"
          + "\002vm\030\002 \001(\tB\003\340A\002\022H\n"
          + "\022vm_creation_config\030d"
          + " \001(\0132*.google.cloud.clouddms.v1.VmCreationConfigH\000\022J\n"
          + "\023vm_selection_config\030e"
          + " \001(\0132+.google.cloud.clouddms.v1.VmSelectionConfigH\000\022\017\n"
          + "\007vm_port\030\003 \001(\005B\013\n"
          + "\tvm_config\"Q\n"
          + "\020VmCreationConfig\022\034\n"
          + "\017vm_machine_type\030\001 \001(\tB\003\340A\002\022\017\n"
          + "\007vm_zone\030\002 \001(\t\022\016\n"
          + "\006subnet\030\003 \001(\t\")\n"
          + "\021VmSelectionConfig\022\024\n"
          + "\007vm_zone\030\001 \001(\tB\003\340A\002\"\033\n"
          + "\tSshScript\022\016\n"
          + "\006script\030\001 \001(\t\"\260\001\n"
          + "\035ListConnectionProfilesRequest\022F\n"
          + "\006parent\030\001 \001("
          + "\tB6\340A\002\372A0\022.datamigration.googleapis.com/ConnectionProfile\022\021\n"
          + "\tpage_size\030\002 \001(\005\022\022\n\n"
          + "page_token\030\003 \001(\t\022\016\n"
          + "\006filter\030\004 \001(\t\022\020\n"
          + "\010order_by\030\005 \001(\t\"\230\001\n"
          + "\036ListConnectionProfilesResponse\022H\n"
          + "\023connection_profiles\030\001"
          + " \003(\0132+.google.cloud.clouddms.v1.ConnectionProfile\022\027\n"
          + "\017next_page_token\030\002 \001(\t\022\023\n"
          + "\013unreachable\030\003 \003(\t\"c\n"
          + "\033GetConnectionProfileRequest\022D\n"
          + "\004name\030\001 \001(\tB6\340A\002\372A0\n"
          + ".datamigration.googleapis.com/ConnectionProfile\"\356\001\n"
          + "\036CreateConnectionProfileRequest\022F\n"
          + "\006parent\030\001 \001(\tB6\340A\002\372A0\n"
          + ".datamigration.googleapis.com/ConnectionProfile\022\"\n"
          + "\025connection_profile_id\030\002 \001(\tB\003\340A\002\022L\n"
          + "\022connection_profile\030\003"
          + " \001(\0132+.google.cloud.clouddms.v1.ConnectionProfileB\003\340A\002\022\022\n\n"
          + "request_id\030\004 \001(\t\"\270\001\n"
          + "\036UpdateConnectionProfileRequest\0224\n"
          + "\013update_mask\030\001 \001(\0132\032.google.protobuf.FieldMaskB\003\340A\002\022L\n"
          + "\022connection_profile\030\002"
          + " \001(\0132+.google.cloud.clouddms.v1.ConnectionProfileB\003\340A\002\022\022\n\n"
          + "request_id\030\003 \001(\t\"\211\001\n"
          + "\036DeleteConnectionProfileRequest\022D\n"
          + "\004name\030\001 \001(\tB6\340A\002\372A0\n"
          + ".datamigration.googleapis.com/ConnectionProfile\022\022\n\n"
          + "request_id\030\002 \001(\t\022\r\n"
          + "\005force\030\003 \001(\010\"\200\002\n"
          + "\021OperationMetadata\0224\n"
          + "\013create_time\030\001 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\0221\n"
          + "\010end_time\030\002 \001(\0132\032.google.protobuf.TimestampB\003\340A\003\022\023\n"
          + "\006target\030\003 \001(\tB\003\340A\003\022\021\n"
          + "\004verb\030\004 \001(\tB\003\340A\003\022\033\n"
          + "\016status_message\030\005 \001(\tB\003\340A\003\022#\n"
          + "\026requested_cancellation\030\006 \001(\010B\003\340A\003\022\030\n"
          + "\013api_version\030\007 \001(\tB\003\340A\0032\310\036\n"
          + "\024DataMigrationService\022\300\001\n"
          + "\021ListMigrationJobs\0222.google.cloud.clouddms.v1.ListMigrationJobsRequest\0323.google.cloud.clouddms.v1.ListMigrationJobsResponse\"B\202\323\344\223\0023\0221/v1/{parent=projects/*/locations/*}/migrationJobs\332A\006parent\022\255\001\n"
          + "\017GetMigrationJob\0220.google.cloud.clouddms.v1.GetMigrationJobRequest\032&.google.cloud.clouddms.v1.MigrationJob\"@\202\323\344\223\0023\0221/v1/{name=projects/*/locations/*/migrationJobs/*}\332A\004name\022\377\001\n"
          + "\022CreateMigrationJob\0223.google.cloud.clouddms.v1.CreateMigrationJobRequest\032\035.google.longrunning.Operation\"\224\001\202\323\344\223\002B\"1/v1/{parent=projects/*/locations/*}/migrationJobs:\r"
          + "migration_job\332A%parent,migration_job,migration_job_id\312A!\n"
          + "\014MigrationJob\022\021OperationMetadata\022\201\002\n"
          + "\022UpdateMigrationJob\0223.google.cloud.clouddms.v1.UpdateMigrationJobRequest\032\035.google.longrunning.Operation\"\226\001\202\323\344\223\002P2?/v1/{migration_job.name=projects/*/locations/*/migrationJobs/*}:\r"
          + "migration_job\332A\031migration_job,update_mask\312A!\n"
          + "\014MigrationJob\022\021OperationMetadata\022\327\001\n"
          + "\022DeleteMigrationJob\0223.google.cloud.clouddms.v1.DeleteMigrationJobRequest\032\035.google.longrunning.Operation\"m\202\323\344\223\0023*1/v1/{name=projects/*/locations/*/migrationJobs/*}\332A\004name\312A*\n"
          + "\025google.protobuf.Empty\022\021OperationMetadata\022\316\001\n"
          + "\021StartMigrationJob\0222.google.cloud.clouddms.v1.StartMigrationJobRequest\032\035.google.longrunning.Operation\"f\202\323\344\223\002<\"7/v1/{name=projects/*/locations/*/migrationJobs/*}:start:\001*\312A!\n"
          + "\014MigrationJob\022\021OperationMetadata\022\313\001\n"
          + "\020StopMigrationJob\0221.google.cloud.clouddms.v1.StopMigrationJobRequest\032\035.google.longrunning.Operation\"e\202\323\344\223\002;\"6/v1/{name=projects/*/locations/*/migrationJobs/*}:stop:\001*\312A!\n"
          + "\014MigrationJob\022\021OperationMetadata\022\321\001\n"
          + "\022ResumeMigrationJob\0223.google.cloud.clouddms.v1.ResumeMigrationJobRequest\032\035.google.longrunning.Operation\"g\202\323\344\223\002=\"8/v1/{name=projects/*/locations/*/migrationJobs/*}:resume:\001*\312A!\n"
          + "\014MigrationJob\022\021OperationMetadata\022\324\001\n"
          + "\023PromoteMigrationJob\0224.google.cloud.clouddms.v1.PromoteMigrationJobRequest\032\035.google.longrunning.Operation\"h\202\323\344\223\002>\"9/v1/{name=projects/*/locations/*/migrationJobs/*}:promote:\001*\312A!\n"
          + "\014MigrationJob\022\021OperationMetadata\022\321\001\n"
          + "\022VerifyMigrationJob\0223.google.cloud.clouddms.v1.VerifyMigrationJobRequest\032\035.google.longrunning.Operation\"g\202\323\344\223\002=\"8/v1/{name=projects/*/locations/*/migrationJobs/*}:verify:\001*\312A!\n"
          + "\014MigrationJob\022\021OperationMetadata\022\324\001\n"
          + "\023RestartMigrationJob\0224.google.cloud.clouddms.v1.RestartMigrationJobRequest\032\035.google.longrunning.Operation\"h\202\323\344\223\002>\"9/v1/{name=projects/*/locations/*/migrationJobs/*}:restart:\001*\312A!\n"
          + "\014MigrationJob\022\021OperationMetadata\022\305\001\n"
          + "\021GenerateSshScript\0222.google.cloud.clouddms.v1.GenerateSshScriptRequest\032#.google.cloud.clouddms.v1.SshScript\"W\202\323\344\223\002Q\"L/v1/{migration_job=projects/*/locations/*/migrationJobs/*}:generateSshScript:\001*\022\324\001\n"
          + "\026ListConnectionProfiles\0227.google.cloud.clouddms.v1.ListConnectionProfilesRequest\0328.google.cloud.clouddms.v1.ListConnectionProfilesResponse\"G\202\323\344\223\0028\0226/v1/{parent=projects/*/locations/*}/connectionProfiles\332A\006parent\022\301\001\n"
          + "\024GetConnectionProfile\0225.google.cloud.clouddms.v1.GetConnectionProfileRequest\032+.google.cloud.clouddms.v1.ConnectionProfile\"E\202\323\344\223\0028\0226/v1/{name=projects/*/locations/*/connectionProfiles/*}\332A\004name\022\242\002\n"
          + "\027CreateConnectionProfile\0228.google.cloud.clouddms.v1.CreateConnectionProfileRequest\032\035.google.longrunning.Operation\"\255\001\202\323\344\223\002L\"6/v1/{parent=projects/*/locations/*}/connectionProfiles:\022connection_profile\332A/parent,connection_profile,connection_profile_id\312A&\n"
          + "\021ConnectionProfile\022\021OperationMetadata\022\244\002\n"
          + "\027UpdateConnectionProfile\0228.google.cloud.clouddms.v1.UpdateConnectionProfileRequest\032\035.google.longrunning.Operation\"\257\001\202\323\344\223\002_2I/v1/{connection_profile.name=projects/*/locations/*/connectionProfiles/*}:\022connection_profile\332A\036connection_profile,update_mask\312A&\n"
          + "\021ConnectionProfile\022\021OperationMetadata\022\346\001\n"
          + "\027DeleteConnectionProfile\0228.google.cloud.clouddms.v1.DeleteConnectionProfileRequest\032\035.google.longrunning.Operation\"r\202\323\344\223\0028*6/v1/{name=projects/*/locations/*/connectionProfiles/*}\332A\004name\312A*\n"
          + "\025google.protobuf.Empty\022\021OperationMetadata\032P\312A\034datamigration.googleapis.com\322A.https://www.googleapis.com/auth/cloud-platformB\305\001\n"
          + "\034com.google.cloud.clouddms.v1B\r"
          + "ClouddmsProtoP\001Z@google.golang.org/genproto/googleapis/cl"
          + "oud/clouddms/v1;clouddms\252\002\030Google.Cloud."
          + "CloudDms.V1\312\002\030Google\\Cloud\\CloudDms\\V1\352\002"
          + "\033Google::Cloud::CloudDMS::V1b\006proto3"
    };
    descriptor =
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(
            descriptorData,
            new com.google.protobuf.Descriptors.FileDescriptor[] {
              com.google.api.AnnotationsProto.getDescriptor(),
              com.google.api.ClientProto.getDescriptor(),
              com.google.api.FieldBehaviorProto.getDescriptor(),
              com.google.api.ResourceProto.getDescriptor(),
              com.google.cloud.clouddms.v1.ClouddmsResourcesProto.getDescriptor(),
              com.google.longrunning.OperationsProto.getDescriptor(),
              com.google.protobuf.FieldMaskProto.getDescriptor(),
              com.google.protobuf.TimestampProto.getDescriptor(),
            });
    internal_static_google_cloud_clouddms_v1_ListMigrationJobsRequest_descriptor =
        getDescriptor().getMessageTypes().get(0);
    internal_static_google_cloud_clouddms_v1_ListMigrationJobsRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_ListMigrationJobsRequest_descriptor,
            new java.lang.String[] {
              "Parent", "PageSize", "PageToken", "Filter", "OrderBy",
            });
    internal_static_google_cloud_clouddms_v1_ListMigrationJobsResponse_descriptor =
        getDescriptor().getMessageTypes().get(1);
    internal_static_google_cloud_clouddms_v1_ListMigrationJobsResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_ListMigrationJobsResponse_descriptor,
            new java.lang.String[] {
              "MigrationJobs", "NextPageToken", "Unreachable",
            });
    internal_static_google_cloud_clouddms_v1_GetMigrationJobRequest_descriptor =
        getDescriptor().getMessageTypes().get(2);
    internal_static_google_cloud_clouddms_v1_GetMigrationJobRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_GetMigrationJobRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_clouddms_v1_CreateMigrationJobRequest_descriptor =
        getDescriptor().getMessageTypes().get(3);
    internal_static_google_cloud_clouddms_v1_CreateMigrationJobRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_CreateMigrationJobRequest_descriptor,
            new java.lang.String[] {
              "Parent", "MigrationJobId", "MigrationJob", "RequestId",
            });
    internal_static_google_cloud_clouddms_v1_UpdateMigrationJobRequest_descriptor =
        getDescriptor().getMessageTypes().get(4);
    internal_static_google_cloud_clouddms_v1_UpdateMigrationJobRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_UpdateMigrationJobRequest_descriptor,
            new java.lang.String[] {
              "UpdateMask", "MigrationJob", "RequestId",
            });
    internal_static_google_cloud_clouddms_v1_DeleteMigrationJobRequest_descriptor =
        getDescriptor().getMessageTypes().get(5);
    internal_static_google_cloud_clouddms_v1_DeleteMigrationJobRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_DeleteMigrationJobRequest_descriptor,
            new java.lang.String[] {
              "Name", "RequestId", "Force",
            });
    internal_static_google_cloud_clouddms_v1_StartMigrationJobRequest_descriptor =
        getDescriptor().getMessageTypes().get(6);
    internal_static_google_cloud_clouddms_v1_StartMigrationJobRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_StartMigrationJobRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_clouddms_v1_StopMigrationJobRequest_descriptor =
        getDescriptor().getMessageTypes().get(7);
    internal_static_google_cloud_clouddms_v1_StopMigrationJobRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_StopMigrationJobRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_clouddms_v1_ResumeMigrationJobRequest_descriptor =
        getDescriptor().getMessageTypes().get(8);
    internal_static_google_cloud_clouddms_v1_ResumeMigrationJobRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_ResumeMigrationJobRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_clouddms_v1_PromoteMigrationJobRequest_descriptor =
        getDescriptor().getMessageTypes().get(9);
    internal_static_google_cloud_clouddms_v1_PromoteMigrationJobRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_PromoteMigrationJobRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_clouddms_v1_VerifyMigrationJobRequest_descriptor =
        getDescriptor().getMessageTypes().get(10);
    internal_static_google_cloud_clouddms_v1_VerifyMigrationJobRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_VerifyMigrationJobRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_clouddms_v1_RestartMigrationJobRequest_descriptor =
        getDescriptor().getMessageTypes().get(11);
    internal_static_google_cloud_clouddms_v1_RestartMigrationJobRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_RestartMigrationJobRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_clouddms_v1_GenerateSshScriptRequest_descriptor =
        getDescriptor().getMessageTypes().get(12);
    internal_static_google_cloud_clouddms_v1_GenerateSshScriptRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_GenerateSshScriptRequest_descriptor,
            new java.lang.String[] {
              "MigrationJob", "Vm", "VmCreationConfig", "VmSelectionConfig", "VmPort", "VmConfig",
            });
    internal_static_google_cloud_clouddms_v1_VmCreationConfig_descriptor =
        getDescriptor().getMessageTypes().get(13);
    internal_static_google_cloud_clouddms_v1_VmCreationConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_VmCreationConfig_descriptor,
            new java.lang.String[] {
              "VmMachineType", "VmZone", "Subnet",
            });
    internal_static_google_cloud_clouddms_v1_VmSelectionConfig_descriptor =
        getDescriptor().getMessageTypes().get(14);
    internal_static_google_cloud_clouddms_v1_VmSelectionConfig_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_VmSelectionConfig_descriptor,
            new java.lang.String[] {
              "VmZone",
            });
    internal_static_google_cloud_clouddms_v1_SshScript_descriptor =
        getDescriptor().getMessageTypes().get(15);
    internal_static_google_cloud_clouddms_v1_SshScript_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_SshScript_descriptor,
            new java.lang.String[] {
              "Script",
            });
    internal_static_google_cloud_clouddms_v1_ListConnectionProfilesRequest_descriptor =
        getDescriptor().getMessageTypes().get(16);
    internal_static_google_cloud_clouddms_v1_ListConnectionProfilesRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_ListConnectionProfilesRequest_descriptor,
            new java.lang.String[] {
              "Parent", "PageSize", "PageToken", "Filter", "OrderBy",
            });
    internal_static_google_cloud_clouddms_v1_ListConnectionProfilesResponse_descriptor =
        getDescriptor().getMessageTypes().get(17);
    internal_static_google_cloud_clouddms_v1_ListConnectionProfilesResponse_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_ListConnectionProfilesResponse_descriptor,
            new java.lang.String[] {
              "ConnectionProfiles", "NextPageToken", "Unreachable",
            });
    internal_static_google_cloud_clouddms_v1_GetConnectionProfileRequest_descriptor =
        getDescriptor().getMessageTypes().get(18);
    internal_static_google_cloud_clouddms_v1_GetConnectionProfileRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_GetConnectionProfileRequest_descriptor,
            new java.lang.String[] {
              "Name",
            });
    internal_static_google_cloud_clouddms_v1_CreateConnectionProfileRequest_descriptor =
        getDescriptor().getMessageTypes().get(19);
    internal_static_google_cloud_clouddms_v1_CreateConnectionProfileRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_CreateConnectionProfileRequest_descriptor,
            new java.lang.String[] {
              "Parent", "ConnectionProfileId", "ConnectionProfile", "RequestId",
            });
    internal_static_google_cloud_clouddms_v1_UpdateConnectionProfileRequest_descriptor =
        getDescriptor().getMessageTypes().get(20);
    internal_static_google_cloud_clouddms_v1_UpdateConnectionProfileRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_UpdateConnectionProfileRequest_descriptor,
            new java.lang.String[] {
              "UpdateMask", "ConnectionProfile", "RequestId",
            });
    internal_static_google_cloud_clouddms_v1_DeleteConnectionProfileRequest_descriptor =
        getDescriptor().getMessageTypes().get(21);
    internal_static_google_cloud_clouddms_v1_DeleteConnectionProfileRequest_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_DeleteConnectionProfileRequest_descriptor,
            new java.lang.String[] {
              "Name", "RequestId", "Force",
            });
    internal_static_google_cloud_clouddms_v1_OperationMetadata_descriptor =
        getDescriptor().getMessageTypes().get(22);
    internal_static_google_cloud_clouddms_v1_OperationMetadata_fieldAccessorTable =
        new com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
            internal_static_google_cloud_clouddms_v1_OperationMetadata_descriptor,
            new java.lang.String[] {
              "CreateTime",
              "EndTime",
              "Target",
              "Verb",
              "StatusMessage",
              "RequestedCancellation",
              "ApiVersion",
            });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.ClientProto.defaultHost);
    registry.add(com.google.api.FieldBehaviorProto.fieldBehavior);
    registry.add(com.google.api.AnnotationsProto.http);
    registry.add(com.google.api.ClientProto.methodSignature);
    registry.add(com.google.api.ClientProto.oauthScopes);
    registry.add(com.google.api.ResourceProto.resourceReference);
    registry.add(com.google.longrunning.OperationsProto.operationInfo);
    com.google.protobuf.Descriptors.FileDescriptor.internalUpdateFileDescriptor(
        descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    com.google.api.ClientProto.getDescriptor();
    com.google.api.FieldBehaviorProto.getDescriptor();
    com.google.api.ResourceProto.getDescriptor();
    com.google.cloud.clouddms.v1.ClouddmsResourcesProto.getDescriptor();
    com.google.longrunning.OperationsProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
